### ISSUE TITLE
Using absolute paths to configuration file

### ISSUE THREAD

**Issue by JoshuaBehrens** [boxblinkracer/phpunuhi#1]
This part always prepends the working directory to the configuration path.

https://github.com/boxblinkracer/phpunuhi/blob/69a62bec5ca562c7701102608508d08b9a3394af/src/Commands/CommandTrait.php#L33-L36

This way I can't provide an absolute path which is sometimes easier to do.

**Comment by boxblinkracer** [comment]
hi there
hehe yeah...you are totally right
didnt test that yet

its more an older copy paste thing of mine as solution for loading files from a .phar scope
there would also be solution for phar, but its not released (yet)

anyway, ill check it out

thanks for helping with this framework

**Comment by JoshuaBehrens** [comment]
You're welcome :)

When it is a 📋 🍝  thing, you have an updated version of that trait? I can imagine a solution with an absolute path check of just use realpath to do its magic.

**Comment by boxblinkracer** [comment]
fixed right?
