### ISSUE TITLE
Wrong shebang in bin script

### ISSUE THREAD

**Issue by hostep** [boxblinkracer/phpunuhi#13]
Hi guys

I've just started testing this package on my system (macOS) and noticed I can't run `vendor/bin/phpunuhi`, I get:
```
/usr/bin/php: bad interpreter: No such file or directory
```

This is because [the shebang at the top of the bin script](https://github.com/boxblinkracer/phpunuhi/blob/235f6e464f8ad29c442f6da7a6fee3fc6ee845f6/bin/phpunuhi#L1) is hardcoded instead of trying to find the correct php binary from the environment.

So the line:
```
#!/usr/bin/php
```

Should be replaced with:
```
#!/usr/bin/env php
```

This is also how other php packages do this, for example:
- https://github.com/sebastianbergmann/phpunit/blob/a5813fb2fc2a69d86fefe4ec2659a00cc3d4c590/phpunit#L1
- https://github.com/composer/composer/blob/ecb69eaa4aec3c2bd866d17ee7a46e684dc16f71/bin/composer#L1
- https://github.com/phpstan/phpstan/blob/7da13f74db97ab5afb1d9d28df4d7c5b9bdca46f/phpstan#L1
- ...

Thanks!

**Comment by boxblinkracer** [comment]
Hi there

a perfect, nice one thank you

ill add it soon

thanks

**Comment by boxblinkracer** [comment]
released in latest version :)

**Comment by hostep** [comment]
Thanks! 🙂

**Comment by boxblinkracer** [comment]
always happy to help :)
