### ISSUE TITLE
Wildcards for filenames

### ISSUE THREAD

**Issue by boxblinkracer** [boxblinkracer/phpunuhi#20]
it would be great to have a

"*" wildcard that merges all found files

            <locales>
                <locale name="en-dev">./**/*.json</locale>
            </locales>

this helps if maaaany json files exist.
Keys and their neting path need to be unique anyway..(if one wants to use this feature)
so a recursive merge before comparing results should be fine.

only filenames cannot be displayed in that case

**Comment by momocode-de** [comment]
@boxblinkracer How exactly does the wildcard work? There is nothing in the documentation about it. This doesn't work for me: 

```
<locales>
    <locale name="de">./Resources/snippet/de_DE/*.de-DE.json</locale>
    <locale name="en">./Resources/snippet/en_GB/*.en-GB.json</locale>
</locales>
```
