### ISSUE TITLE
Protect markers

### ISSUE THREAD

**Issue by htuscher** [boxblinkracer/phpunuhi#22]
If you have translation markers e.g. `The name of the product is %productName%`. 
The placeholder `%productName%` should be protected from translation via translation services.

**Comment by boxblinkracer** [comment]
aaa thats a good one, thx @hhoechtl 
ill add it :)

would make sense to configure the marker right?

**Comment by htuscher** [comment]
Yes I think other systems have different markers .e.g. `###marker###`

**Comment by boxblinkracer** [comment]
hey @hhoechtl 

can you double check my screenshot (readme).
not quite sure about the place for the configuration, also dont like the long names

what is your opinion on that? attribute in format? or in the rules?
also we need start + end markers i think :) 

thx for your help

<img width="973" alt="Screenshot 2023-04-26 at 17 13 48" src="https://user-images.githubusercontent.com/5579326/234621280-9fb5246c-cda9-4fe6-93ad-681ab6b64649.png">

**Comment by htuscher** [comment]
@boxblinkracer I would maybe go even further. What do you think about something like this?

```xml
<set name="sample">
  <protect>
    <marker start="{" end="}" />
    <marker start="{%" end="%}" />
    <term>Shopware</term>
    <term>iPhone</term>
  </protect>
```

**Comment by boxblinkracer** [comment]
uuuuuu brilliant. 
gekauft ;)
ill do it in that way. thanks a lot

**Comment by boxblinkracer** [comment]
done, ready on master and will come with next release
again, thank you for this great idea :)
