### ISSUE TITLE
Add Support for categories and shopping experiences in shopware 6 storage format

### ISSUE THREAD

**Issue by FalkoHilbert** [boxblinkracer/phpunuhi#48]
Hi,

In Shopware 6, in addition to the translations of various entities (usually in the `[...]_translation` table), there is also the option of assigning categories and products layouts from the shopping experiences area. As soon as this has been done, you have the option of storing various other fields with content in the respective language in each category and each product. This data is stored for categories, for example, in the `category_translation` table in the `slot_config` field as json.

Here we have the challenge that this data, preferably in CSV format, should also be sent to an external translator.

It would therefore be very helpful if there was a way to export and import this data with PHPUnuhi.

**Comment by boxblinkracer** [comment]
Hi there

so all entitities with _translation are now working in v1.20.0
can you check that?

thank you :)
