### ISSUE TITLE
Make translations node optional if imports are used

### ISSUE THREAD

**Issue by momocode-de** [boxblinkracer/phpunuhi#52]
I would like to configure all my translation sets in sub-files and then import them into a main file. However, no extra set should be configured in the main file. This is currently not possible as the “translations” node is required.

**Comment by boxblinkracer** [comment]
Hi

oh, that seems to be a bug
it should be possible to of course only use import files

ill check it out
thanks for this

**Comment by boxblinkracer** [comment]
Hi

thank you again
it has been fixed and is ready in dev-master
will be part of the next release

**Comment by boxblinkracer** [comment]
has been released in 1.21.0
