### ISSUE TITLE
BUG:  PHP 8.3 Invalid return type in FixSpellingCommand -> execute function | shall have return type int

### ISSUE THREAD

**Issue by griesi007** [boxblinkracer/phpunuhi#61]
src\Commands\FixSpellingCommand.php on line 53

public function execute must have return type int

Fatal error: Declaration of PHPUnuhi\Commands\FixSpellingCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int

**Comment by boxblinkracer** [comment]
done in dev-master
thanks for letting me know
