### ISSUE TITLE
BUG JsonLoader should no clear existing translation when json file has syntax errors 

### ISSUE THREAD

**Issue by griesi007** [boxblinkracer/phpunuhi#62]
Currently json loader ignores json_decode syntax errors in JsonLoader::loadTranslations (26) and clears out all all translations which were in the file. Instead JsonLoader should trigger an error and stop proceeding.

e.g.
{
      "key1": "translation1",
}  

becomes
{
      "key1": ""
}

**Comment by boxblinkracer** [comment]
thanks for this :) great finding

**Comment by boxblinkracer** [comment]
released in v1.22.0
